name: Go Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.1'

    - name: Cache Go Modules
      uses: actions/cache@v3
      with:
        path: |
          ~/go/pkg/mod
          ~/.cache/go-build
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Download Dependencies
      run: go mod download

    - name: Set Up CI Environment Variables
      run: |
        echo "Setting up CI environment file"
        echo "RPC=${{ secrets.RPC }}" > .env.ci
        echo "PRIVATE_KEY=${{ secrets.KEYS }}" >> .env.ci

    - name: Build
      run: go build

    - name: Run Tests
      env:
        ENV_PATH: .env.ci
      run: go test ./...

    - name: List Files
      run: ls -la

    - name: Verify Build
      run: |
        ./slurpy --help  || (echo "Build failed or binary not found!" && exit 1)
