name: Go Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.1'

    - name: Build
      run: go build -o slurpy -v ./...

    - name: Run Tests
      run: go test -v ./...

    - name: Verify Build
      run: |
        if [ ! -f ./slurpy ]; then
          echo "Build failed or binary not found!"
          exit 1
